apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: music-charts
type: Opaque
stringData:
  password: "musicpass"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: music-charts
type: Opaque
stringData:
  password: "mongopass"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: music-charts
type: Opaque
stringData:
  secret_key: "your-secret-key-minimum-32-characters-change-in-production"

